### ISSUE TITLE
Migrate to stabilized x86/x86_64 SIMD

### ISSUE THREAD

**Issue by sunchao** [sunchao/parquet-rs#113]
Currently the SIMD feature requires the `x86intrin` crate and a compile time flag `RUSTFLAGS="-C target-feature=+sse4.2"`. Since [x86/x86_64 SIMD is already stabilized](https://github.com/rust-lang/rust/pull/49664), we should no longer need this crate dependency, and more importantly, enable feature check at run time via the command: `is_x86_feature_detected`.

**Comment by sadikovi** [comment]
That is great! I am curious if there is a nightly release with this PR already. Will update my Rust version!
