### ISSUE TITLE
Writing?

### ISSUE THREAD

**Issue by adrianN** [sunchao/parquet-rs#114]
This crate doesn't seem to support writing Parquet files. Is this planned? I'd like to convert CSV files to Parquet.

**Comment by sadikovi** [comment]
No, it does not support writes as of release 0.3.0. I was going to start working on it in the coming days.

**Comment by adrianN** [comment]
Awesome!

**Comment by sadikovi** [comment]
I am going to close this issue, I opened the RFC issue #116, the progress will be tracked there.
Hopefully, no objections, and everyone do have a good day!
