### ISSUE TITLE
Static lifetime issues

### ISSUE THREAD

**Issue by gnieto** [sunchao/parquet-rs#143]
While working on adding support to read from a generic `Read`, I've found that there are some usability issues derived from the usage of  `'static` lifetime and/or `Box`ing.

For example, even if the reader is now generic, only static data can be parsed from a cursor. You can see an example on the description of this PR: https://github.com/sunchao/parquet-rs/pull/142

**Comment by sadikovi** [comment]
Then I do not see the point of merging PR until we fix the underlying problem. Otherwise, there is not much use of that work. We should scope the work and come up with subtasks, if possible.

**Comment by sunchao** [comment]
Closing this as the related PR is merged already. @gnieto : feel free to re-open if you think there's more issues related to static lifetime.
