### ISSUE TITLE
How to get column name

### ISSUE THREAD

**Issue by jcgomes90** [sunchao/parquet-rs#200]
I am trying to write out a parquet file with a schema that will have many fields:

```
let message_type = "message schema"
{
     REQUIRED DOUBLE a;
     OPTIONAL DOUBLE b;
     ...
}
```
I am iterating through the row columns as below. 

```
let mut row_group_writer = serialized_writer.next_row_group().unwrap();
while let Some(mut col_writer) = row_group_writer.next_column().unwrap()
{
     ...
}
```

I want to read the column name of the schema (ie. 'a'). Ideally have a match statement within the while loop for the column name. I read through the parquet-rs documentations and couldn't find a way to do this. Is this possible? Is there an alternative method?

**Comment by sunchao** [comment]
When you initialize the file writer, you'd pass a schema to it right? you should be able to get the field name from the schema I think.

**Comment by jcgomes90** [comment]
Is it possible to get the field name of the column when doing the writes?
