### ISSUE TITLE
Remove arena crate dependency

### ISSUE THREAD

**Issue by xrl** [sunchao/parquet-rs#209]
The `src/lib.rs` has a `extern crate arena` line. Where is that used? I looked for use of the arena crate and I didn't find anything.

If I remove it, the `parquet-read`/`parquet-schema` binary executables don't need any dylib paths.

With arena:

```
$ cargo install --force
$ ~/.cargo/bin/parquet-schema 
dyld: Library not loaded: @rpath/libarena-9fcb98fa681bdaef.dylib
  Referenced from: /Users/xavierlange/.cargo/bin/parquet-schema
  Reason: image not found
Abort trap: 6
```

Without arena:

```
$ cargo install --force
$ ~/.cargo/bin/parquet-schema 
Usage: parquet-schema <file-path> [verbose]
```

Are we open to removing the `extern crate arena` line from `src/lib.rs`?

**Comment by sunchao** [comment]
Good point. We don't need the line. It is already removed in the [arrow](https://github.com/apache/arrow/blob/master/rust/src/lib.rs) project though.

**Comment by xrl** [comment]
Cool, closing!
