### ISSUE TITLE
parquest-format-rs changes their type formats

### ISSUE THREAD

**Issue by toshitanian** [sunchao/parquet-rs#212]
https://github.com/sunchao/parquet-format-rs/commit/63daa55cfd63c94b73000d75087f2522d2bacef6

**Comment by sunchao** [comment]
Yes. This is updated accordingly in [Arrow](https://github.com/apache/arrow/tree/master/rust), where this repo has migrated to.

**Comment by toshitanian** [comment]
Ok, I didn't know that this repo is deprecated. Thank you
