### ISSUE TITLE
File coverage is not shown on coveralls

### ISSUE THREAD

**Issue by sadikovi** [sunchao/parquet-rs#27]
When I look up coverage per file for a commit, coveralls reports following:

_The file "file/metadata.rs" isn't available on github. Either it's been removed, or the repo root directory needs to be updated._

I found that one could set repository root directory in coveralls: https://github.com/lemurheavy/coveralls-public/issues/886#issuecomment-266094774

@sunchao Could you have a look and possibly fix it in coveralls? So we can see what lines are not covered and add more unittests.

**Comment by sadikovi** [comment]
I will try it on a sample repository to see if it actually works.

**Comment by sunchao** [comment]
@sadikovi Yes I noticed this too. Will look into this.

**Comment by sunchao** [comment]
@sadikovi It is working now after setting the sub directory. Thanks for raising this issue!

**Comment by sadikovi** [comment]
It works! Thanks for fixing it!
