### ISSUE TITLE
Publish to Crates.io

### ISSUE THREAD

**Issue by sunchao** [sunchao/parquet-rs#71]
With #67 resolved, I think we are ready to publish an initial version to Crates.io. @sadikovi : what do you think?

**Comment by andygrove** [comment]
In my opinion, it's almost never too early to publish. It makes it much easier for people to start pulling this in as a dependency and start experimenting.

**Comment by sunchao** [comment]
Yes agreed. Especially as we have the record API and binaries to read metadata & rows now. This is a good time to publish and for people to try it out.

**Comment by andygrove** [comment]
Great timing for me too, since my Rust implementation of Apache Arrow just got merged to the main repo ;-)

**Comment by sunchao** [comment]
Cool! I think we are going to try it out here :)

**Comment by sadikovi** [comment]
@sunchao sorry for the late response. Nice! We should definitely do this, so people could start trying it out! I don’t know how publish on crates works though.

@andygrove could you comment on your plan for using your implementation with parquet-rs? I saw a couple of other Rust implementations for arrow, so I am a bit confused.

**Comment by andygrove** [comment]
@sadikovi My PR is now the official Rust implementation of Arrow. I did draw some inspiration from other implementations and worked with some of those authors to get this PR in place. I expect others will start contributing soon.

My interest in Arrow and Parquet is for my project https://github.com/andygrove/datafusion-rs

I haven't stared using parquet-rs yet so don't know specifically what the integration will look like.

**Comment by sunchao** [comment]
The crate is [published](https://crates.io/crates/parquet)!

**Comment by sadikovi** [comment]
Great! Thanks a lot! 🎉

**Comment by sadikovi** [comment]
I assume that our plan also includes publishing documentation somewhere - I saw most of the crates doing it on `docs.rs` (I do not know if we would need to pay for it). I will try working on documentation updates next week.

**Comment by sunchao** [comment]
@sadikovi: Yes you are right - we also need to improve the document on the source code. Another thing is to think about what APIs we should expose to public.

BTW: do you have a username on the Crates.io?

**Comment by sadikovi** [comment]
Yes, you are right. We have a TODO on exposing only public items and hiding internal details. I will addressing that as well.

I logged in with my github account on crates.io.
