### ISSUE TITLE
Suggestion: Add examples

### ISSUE THREAD

**Issue by andygrove** [sunchao/parquet-rs#77]
With a new Rust project I usually go look at the examples first. I think it would be helpful to have some simple examples for reading parquet files. Perhaps one column-oriented and one row-oriented?

**Comment by sadikovi** [comment]
Thanks @andygrove. You are right, some sort of doc reference would be very helpful.

We are going to publish crate documentation and possibly README update that includes examples of using column reader API and record reader API. I am currently working on it in `update-documentation` branch, will try finishing it by next week.

**Comment by sadikovi** [comment]
If you need some reference right away, I suggest you look at https://github.com/sunchao/parquet-rs/blob/master/src/bin/parquet-read.rs for getting records and what types are available (https://github.com/sunchao/parquet-rs/blob/master/src/record/api.rs). 

For column reader API, I suggest looking at https://github.com/sunchao/parquet-rs/blob/master/src/column/reader.rs#L44 and triplet functionality that uses column readers (https://github.com/sunchao/parquet-rs/blob/master/src/record/triplet.rs#L205).

I hope that helps you meanwhile.

**Comment by sadikovi** [comment]
I created an issue for this that I am working on currently #78.
