### ISSUE TITLE
Update crate documentation

### ISSUE THREAD

**Issue by sadikovi** [sunchao/parquet-rs#78]
Currently we do not publish documentation when releasing a new version of crate. It would be very useful for people to get started, if we had one.

Items to cover:
- Compile documentation for crate, so it can be published, e.g. module documentation, structs, methods, etc.
- Add some references in README.
- Add badge to point to the latest docs.
- Fix docs.rs build somehow (?), see comments below.

**Comment by andygrove** [comment]
You probably already know this, but docs.rs published some docs for you here:

https://docs.rs/crate/parquet/0.1.0

If couldn't produce code documentation though because the build failed:

https://docs.rs/crate/parquet/0.1.0/builds/94072

**Comment by sadikovi** [comment]
Oh, thanks! Documentation still needs updates though, this is a good start.
We need to attach the badge and also fix how documentation is built. I am wondering if there is some sort of step to publish documentation manually, instead of running automatic doc build.

**Comment by sadikovi** [comment]
@sunchao would you mind to comment on what we do with thrift not being installed when building docs? I am not sure, if there is a way to configure docs.rs to install thrift first. 

I was also thinking that we could technically install thrift in build.rs script, if one does not already exist.

**Comment by sunchao** [comment]
It seems hard to publish to docs.rs without building it - installing thrift may not work since it requires sudo privilege.

Another option is to publish to github pages, like mentioned [here](https://users.rust-lang.org/t/whats-the-best-documentation-solution-other-than-docs-rs/16211).

**Comment by sadikovi** [comment]
@sunchao Thanks! This looks like a really good alternative and we have Travis set up already for builds, so it should be relatively easy to configure github pages.

**Comment by sunchao** [comment]
Yes. And another alternative is to attach the generated `parquet.rs` to each release (like the [release 0.1.0](https://github.com/sunchao/parquet-rs/releases/tag/0.1.0)) **before** publishing it to crates.io, and add an option in build.rs to download the file instead of compiling thrift, perhaps only for the docs.rs case.

Not sure if this could work though.

**Comment by sadikovi** [comment]
I like your suggestion about travis + github pages alternative, but would not mind any option that works and results in minimal amount of effort for us:). I could not find a difference between changes in recent release 0.1.0 compared to the previous release... did you manually include parquet.rs? We might need to disable build.rs in this case, but I am not sure:)

**Comment by sunchao** [comment]
> I could not find a difference between changes in recent release 0.1.0 compared to the previous release..

Hmm.. what do you mean, 0.1.0 is the first release we have.

> did you manually include parquet.rs


Yes I had to manually upload the `parquet.rs`.

> We might need to disable build.rs in this case, but I am not sure:)


We can add a feature tag (such as `[doc]`, see [here for detailed info about feature tag](https://doc.rust-lang.org/cargo/reference/manifest.html)) in the `Cargo.toml` which will provide a `#[cfg(feature = doc)]`. This can potentially be used in `build.rs` to skip the thrift compiling and download the `parquet.rs`.

We can then add `[doc] to `package.metadata.docs.rs` which will be picked up by `docs.rs` to call `build.rs` as specified.

I'm fine with the travis + github pages approach too which seems really simple.

**Comment by sadikovi** [comment]
I meant previous 0.1.0 release. All good, I suggest we wait until I open PR with documentation update and then we decide how to publish:). Thanks for the help!

**Comment by sunchao** [comment]
NP. Sounds good.
