### ISSUE TITLE
Process statistics for column chunk metadata and data page headers

### ISSUE THREAD

**Issue by sadikovi** [sunchao/parquet-rs#83]
There is a TODO that I think we should complete to have full featured read support. 

https://github.com/sunchao/parquet-rs/blob/master/src/file/metadata.rs#L268
https://github.com/sunchao/parquet-rs/blob/master/src/file/reader.rs#L357

Also take into consideration https://github.com/sunchao/parquet-rs/blob/master/src/file/reader.rs#L332.

Will work on it.

**Comment by sunchao** [comment]
Yes stats will be an important piece. This will also unlock various predicate pushdowns in future.
